import datetime

# -----------------------------
# File paths
xyz_file = "cord_cnt.xyz"
output_file = "input_cnt_without_topology.txt"
# -----------------------------

# Read coordinates from XYZ file
coordinates = []
with open(xyz_file, "r") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) >= 3:
            x, y, z = map(float, parts[:3])
            coordinates.append((x, y, z))

num_atoms = len(coordinates)

# Map atom ID to coordinates (1-indexed)
id_to_pos = {i+1: coord for i, coord in enumerate(coordinates)}



# Box dimensions (example, can be adjusted)
xlo, xhi = -60.0, 60.0
ylo, yhi = -40.0, 40.0
zlo, zhi = -40.0, 40.0

# Types (example, all 1)
atom_types = 1

# Write LAMMPS input file
with open(output_file, "w") as f:
    # Header
    f.write(f"LAMMPS data file. CGCMM style. atom_style molecular generated by Python script on {datetime.datetime.now().strftime('%a %b %d %H:%M:%S %Y')}\n")
    f.write(f"{num_atoms} atoms\n")
    f.write(f"{atom_types} atom types\n")
    f.write(f"{xlo} {xhi} xlo xhi\n")
    f.write(f"{ylo} {yhi} ylo yhi\n")
    f.write(f"{zlo} {zhi} zlo zhi\n\n")

    # Masses
    f.write("Masses\n\n")
    f.write("1 12.0107\n\n")

    # Atoms
    f.write("Atoms # molecular\n\n")
    for idx, (x, y, z) in enumerate(coordinates, 1):
        f.write(f"{idx} 1  {x:.6f} {y:.6f} {z:.6f}\n")
    f.write("\n")

print(f"LAMMPS input file '{output_file}' generated successfully!")

