import datetime

# -----------------------------
# File paths
xyz_file = "cord_cnt.xyz"
topology_file = "cnt_full_topology.txt"
output_file = "input_cnt_with_topology.txt"
# -----------------------------

# Read coordinates from XYZ file
coordinates = []
with open(xyz_file, "r") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) >= 3:
            x, y, z = map(float, parts[:3])
            coordinates.append((x, y, z))

num_atoms = len(coordinates)

# Map atom ID to coordinates (1-indexed)
id_to_pos = {i+1: coord for i, coord in enumerate(coordinates)}

# Read topology file in the style you provided
# Read topology file in the style you provided
bonds = []
angles = []
dihedrals = []
impropers = []
body = {}  # store body index for atoms

section = None
with open(topology_file, "r") as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("#") or line.lower().startswith("summary"):
            continue

        # Detect sections
        if line.lower().startswith("bonds"):
            section = "bonds"
            continue
        elif line.lower().startswith("angles"):
            section = "angles"
            continue
        elif line.lower().startswith("dihedrals"):
            section = "dihedrals"
            continue
        elif line.lower().startswith("impropers"):
            section = "impropers"
            continue

        # Parse according to section
        parts = line.split()
        if section == "bonds":
            # Format: index a1 a2 body x1 y1 z1 x2 y2 z2
            _, a1, a2, bidx = map(int, parts[:4])
            bonds.append((a1, a2))
            body[a1] = bidx
            body[a2] = bidx
        elif section == "angles":
            # Format: index A B C body xA yA zA xB yB zB xC yC zC
            _, A, B, C, bidx = map(int, parts[:5])
            angles.append((A, B, C))
            body[B] = bidx
        elif section == "dihedrals":
            # Format: index A B C D body xA yA zA ... xD yD zD
            _, A, B, C, D, bidx = map(int, parts[:6])
            dihedrals.append((A, B, C, D))
            body[B] = bidx
        elif section == "impropers":
            # Format: index n1 center n2 n3 body x1 y1 z1 ... x3 y3 z3
            _, n1, center, n2, n3, bidx = map(int, parts[:6])
            impropers.append((center, n1, n2, n3))
            body[center] = bidx


# Counts
num_bonds = len(bonds)
num_angles = len(angles)
num_dihedrals = len(dihedrals)
num_impropers = len(impropers)

# Box dimensions (example, can be adjusted)
xlo, xhi = -60.0, 60.0
ylo, yhi = -40.0, 40.0
zlo, zhi = -40.0, 40.0

# Types (example, all 1)
atom_types = 1
bond_types = 1
angle_types = 1
dihedral_types = 1
improper_types = 1

# Write LAMMPS input file
with open(output_file, "w") as f:
    # Header
    f.write(f"LAMMPS data file. CGCMM style. atom_style molecular generated by Python script on {datetime.datetime.now().strftime('%a %b %d %H:%M:%S %Y')}\n")
    f.write(f"{num_atoms} atoms\n")
    f.write(f"{num_bonds} bonds\n")
    f.write(f"{num_angles} angles\n")
    f.write(f"{num_dihedrals} dihedrals\n")
    f.write(f"{num_impropers} impropers\n")
    f.write(f"{atom_types} atom types\n")
    f.write(f"{bond_types} bond types\n")
    f.write(f"{angle_types} angle types\n")
    f.write(f"{dihedral_types} dihedral types\n")
    f.write(f"{improper_types} improper types\n")
    f.write(f"{xlo} {xhi} xlo xhi\n")
    f.write(f"{ylo} {yhi} ylo yhi\n")
    f.write(f"{zlo} {zhi} zlo zhi\n\n")

    # Masses
    f.write("Masses\n\n")
    f.write("1 12.0107\n\n")

    # Atoms
    f.write("Atoms # molecular\n\n")
    for idx, (x, y, z) in enumerate(coordinates, 1):
        f.write(f"{idx} 1 1 {x:.6f} {y:.6f} {z:.6f}\n")
    f.write("\n")

    # Bonds
    f.write("Bonds\n\n")
    for i, (a1, a2) in enumerate(bonds, 1):
        f.write(f"{i} 1 {a1} {a2}\n")
    f.write("\n")

    # Angles
    f.write("Angles\n\n")
    for i, (A, B, C) in enumerate(angles, 1):
        f.write(f"{i} 1 {A} {B} {C}\n")
    f.write("\n")

    # Dihedrals
    f.write("Dihedrals\n\n")
    for i, (A, B, C, D) in enumerate(dihedrals, 1):
        f.write(f"{i} 1 {A} {B} {C} {D}\n")
    f.write("\n")

    # Impropers
    f.write("Impropers\n\n")
    for i, (center, n1, n2, n3) in enumerate(impropers, 1):
        f.write(f"{i} 1 {center} {n1} {n2} {n3}\n")

print(f"LAMMPS input file '{output_file}' generated successfully!")

